# Generated by Django 3.2 on 2023-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_userinfo_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户列表'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
