# Generated by Django 3.2 on 2023-04-29 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20230428_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('nowCity', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ShipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('build_time', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.port')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.shiptype')),
            ],
            options={
                'verbose_name': '船舶列表',
            },
        ),
    ]
