# Generated by Django 3.2 on 2023-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_remove_shipinfo_build_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipinfo',
            name='speed',
            field=models.IntegerField(default=50),
        ),
    ]
