# Generated by Django 3.2 on 2023-04-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
