# Generated by Django 3.2 on 2023-04-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_rename_user_id_cargo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
