# Generated by Django 3.2 on 2023-04-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
