# Generated by Django 3.2 on 2023-05-02 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成'), (6, '已取消')], default=1, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('distance', models.IntegerField()),
                ('is_commented', models.BooleanField(default=False, verbose_name='是否评价了')),
                ('comment', models.SmallIntegerField(choices=[(0, '0分'), (1, '20分'), (2, '40分'), (3, '60分'), (4, '80分'), (5, '100分')], default=1, verbose_name='订单状态')),
                ('Remark', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.cargo')),
                ('end_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_port', to='app01.port')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.shipinfo')),
                ('start_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_port', to='app01.port')),
            ],
        ),
    ]
