# Generated by Django 3.2 on 2023-05-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_alter_order_ordernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kuaidiNum',
            field=models.CharField(default='', max_length=50),
        ),
    ]
