# Generated by Django 3.2 on 2023-05-02 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_order_kuaidinum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
