# Generated by Django 3.2 on 2023-05-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Remark',
            field=models.TextField(),
        ),
    ]
